default_language_version:
  python: python3.8

ci:
  autofix_prs: true
  autoupdate_commit_msg: '[pre-commit.ci] pre-commit suggestions'
  autoupdate_schedule: quarterly

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-yaml
      - id: check-case-conflict
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: trailing-whitespace
#  - repo: https://github.com/PyCQA/pydocstyle todo decomment and add api docs
#    rev: 6.1.1
#    hooks:
#      - id: pydocstyle
#        name: Check docs
#        files: ^classy/
#        language_version: python3.8
#        args: ["--convention=google"]
  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: Format imports
        files: ^classy/
        args: ["--profile", "black"]
  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black
        name: Format code
        files: ^classy/
  - repo: https://github.com/asottile/blacken-docs
    rev: v1.12.1
    hooks:
      - id: blacken-docs
        name: Format code in docs
        additional_dependencies: [ black==21.12b0 ]
