supported_tasks:
  - qa
  - sentence-pair
  - sequence
  - token
  - generation

# global params
transformer_model: facebook/bart-large

# trainer
training:
  pl_trainer:
    accumulate_grad_batches: 1
    val_check_interval: 1.0
    max_steps: 100_000

# MODEL PARAMS
model:
  optim_conf:
    _target_: classy.optim.factories.RAdamFactory
    lr: 1e-5
    weight_decay: 0.01
    no_decay_params:
      - bias
      - LayerNorm.weight
