_target_: 'classy.pl_modules.hf.classification.HFSentencePairPLModule'
transformer_model: ${transformer_model}
additional_special_tokens: []
optim_conf:
  _target_: classy.optim.factories.RAdamFactory
  lr: 1e-5
  weight_decay: 0.01
  no_decay_params:
    - bias
    - LayerNorm.weight
