_target_: 'classy.pl_modules.hf.classification.HFTokensPLModule'
transformer_model: ${transformer_model}
additional_special_tokens: []
use_last_n_layers: 1
fine_tune: True
optim_conf:
  _target_: classy.optim.factories.RAdamFactory
  lr: 1e-5
  weight_decay: 0.01
  no_decay_params:
    - bias
    - LayerNorm.weight
