- _target_: "classy.pl_callbacks.prediction.PredictionPLCallback"
  validation_path: null
  prediction_confs:
    - name: "validation"
      path: null  # if you leave it to None, it will be set to the validation path
      token_batch_size: 400
      prediction_param_conf_path: "configurations/prediction-params/generation-beam.yaml"
      limit: 1000
      enabled_prediction_callbacks:
        - "file_dumper"
  prediction_callbacks:
    file_dumper:
      _target_: "classy.pl_callbacks.prediction.FileDumperPredictionCallback"
  prediction_dataset_conf: ${prediction.dataset}
